version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/ai-workflow"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/consumer"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/webapp"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    versioning-strategy: increase

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
