name = "cf-workers-telegram-bot-v2"
main = "src/main.ts"

workers_dev = true
compatibility_date = "2025-06-04"

[ai]
binding = "AI"

[observability.logs]
enabled = true

[observability.traces]
enabled = true

[[kv_namespaces]]
binding = "CONVERSATION_HISTORY"
id = "7c147881ce7d42b8811bfbf8c38e3ee4"

[[r2_buckets]]
binding = "R2"
bucket_name = "share"
