name: publish nightly

on:
  push:
    branches:
      - master

jobs:
  publish-nightly:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          registry-url: https://npm.pkg.github.com/
          scope: "@codebam"
      - id: node-modules-cache
        uses: actions/cache@v4
        with:
          path: |
            node_modules
          key: node-modules-${{ hashFiles('package-lock.json') }}
          restore-keys: node-modules-
      - run: npm i
      - run: npm ci
      - name: Update version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          SHA=$(git rev-parse --short HEAD)
          NIGHTLY_VERSION="${VERSION}-nightly.${SHA}"
          echo "Publishing version $NIGHTLY_VERSION"
          npm version $NIGHTLY_VERSION --no-git-tag-version
      - run: npm run build
      - run: npm publish --tag nightly
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
